### ISSUE TITLE
Is there a way to tweak the plugin in order to get access to tag_list anywhere on the website?

### ISSUE THREAD

**Issue by e-mln-e** [danreeves/picotags#16]
Sorry, this might be a complete newbie question. I'm new to php (and to pico actually...), and I've tried to remove the conditional   if ($this->is_tag)   but it doesn't seem to work - and doesn't provide an error. Thank you by advance!

**Comment by danreeves** [comment]
Try setting line 153 and 236 to ` if (true) {`.

A workaround in the template would work, but it would have duplicates:

```
{% for page in pages %}
    {% for tag in page.tags %}
        {{ tag }}
    {% endfor %}
{% endfor %}
```

**Comment by danreeves** [comment]
Try setting line 153 and 236 to ` if (true) {`.

A workaround in the template would work, but it would have duplicates:

```
{% for page in pages %}
    {% for tag in page.tags %}
        {{ tag }}
    {% endfor %}
{% endfor %}
```

**Comment by danreeves** [comment]
Try setting line 153 and 236 to ` if (true) {`.

A workaround in the template would work, but it would have duplicates:

```
{% for page in pages %}
    {% for tag in page.tags %}
        {{ tag }}
    {% endfor %}
{% endfor %}
```

**Comment by danreeves** [comment]
Try setting line 153 and 236 to ` if (true) {`.

A workaround in the template would work, but it would have duplicates:

```
{% for page in pages %}
    {% for tag in page.tags %}
        {{ tag }}
    {% endfor %}
{% endfor %}
```

**Comment by e-mln-e** [comment]
That way, it does display the tag_list elsewhere, but disrupts the display of posts on any page that isn't a tag page.
Typically, this page (http://emelinebrule.net/Everything) should display all posts, in this part of the template
<pre><code>
<section id="articles">
   {% for page in pages %}
      {% if page.date %}
         [...]
      {% endif %}
   {% endfor %}
</section>
</code></pre>
... but doesn't :)
Although another workaround would be to add an "everything" tag to all posts, I was wondering if there was a clean way of doing so.

**Comment by danreeves** [comment]
Can you try with this file: https://github.com/danreeves/picotags/blob/global-tag-list/picotags.php

Thanks

**Comment by e-mln-e** [comment]
Tried it, but it disrupts the display as well. Actually somehow it gets in conflict with the retrieving of informations in general. The page does not get the title of the page for the metadata either.

**Comment by danreeves** [comment]
How does https://github.com/danreeves/picotags/blob/global-tag-list/picotags.php work now?

**Comment by e-mln-e** [comment]
It works like a charm! Thank you so much! I'm digging into your modifications to understand that magic ;)

**Comment by danreeves** [comment]
No problem. I'll merge the changes back into master and close that branch.

The biggest difference is doing collecting all the tags this page loop and adding it to the context.
https://github.com/danreeves/picotags/commit/9951c6f3b6d13d0f50dbc8f5b0dc9d949c00df59#diff-10bfd5e0c14675b706e030f7e1973488R229
