### ISSUE TITLE
Empty element in tags array if no tags

### ISSUE THREAD

**Issue by sookoll** [danreeves/picotags#19]
If page do not have any tags, tags array contain one empty element:

```
{{ page.tags|length }}
```

shows 1.

**Comment by bricebou** [comment]
Hi,

In the header of your page, have you "Tags: " (with an empty list) ?

**Comment by sookoll** [comment]
No matter is there Tags: (no values) or no Tags attribute at all. Currently I just
´´´´
{% if tags|length > 1 %}
´´´´
to overcome this issue.

**Comment by bricebou** [comment]
@sookoll excuse me for the delay of this answer but could you please tell us what version of Pico you are using and give us the complete code you are using ?

Anyway, if you want to check that the tag variable is set, why don't you just use `{% if meta.tags %}` ?

**Comment by sookoll** [comment]
Pico 0.9
https://github.com/sookoll/sookoll.ee/blob/master/pico/themes/sookoll/index.html#L49

**Comment by danreeves** [comment]
I've just pushed a fix in commit 3f8b2ca. Can you let me know if that solves the issue.

Thanks

**Comment by sookoll** [comment]
Hi, nice work. Haven't tested it yet, but it should do the trick. Also one possible solution is described here:
http://icefront.info/blog/explode-empty-string-returns-one-element-array/

**Comment by danreeves** [comment]
Implemented it like that, much cleaner. You can reopen if the issue persists.

Thanks
